version: 2.1

orbs:
  ssh-deployment: singularitynet/ssh-deployment@2.4.1

jobs:
  cntk-next-day-trend:
    docker:
      - image: circleci/python:3.6.6-node
    steps:
      - checkout
      - ssh-deployment/deploy:
          ssh-host: ${SSH_HOST}
          ssh-user: ${SSH_USER}
          service-dir: "finance/cntk-next-day-trend"
          mainnet-port: "7018"
          testnet-port: "7051"
          run-command: "source '/cntk/activate-cntk';python3 run_service.py --ssl --metering"
          docker-test-files: "Dockerfile, requirements.txt"
          docker-file-path: "finance/cntk-next-day-trend/Dockerfile"
          docker-no-cache: true
          docker-image: "cntk_next_day_trend"
          docker-container: "CNTK_NEXT_DAY_TREND"
          docker-nvidia: true
          docker-volumes: "-v ~/singnet/.certs:/opt/singnet/.certs"
          daemon-version: ${CI_SNETD_VERSION}
          daemon-pk: ${PK_CNTK_NEXT_DAY_TREND}
  cntk-lstm-forecast:
    docker:
      - image: circleci/python:3.6.6-node
    steps:
      - checkout
      - ssh-deployment/deploy:
          ssh-host: ${SSH_HOST}
          ssh-user: ${SSH_USER}
          service-dir: "generic/cntk-lstm-forecast"
          mainnet-port: "7017"
          testnet-port: "7059"
          run-command: "source '/cntk/activate-cntk';python3 run_service.py --ssl --metering"
          docker-test-files: "Dockerfile, requirements.txt"
          docker-file-path: "generic/cntk-lstm-forecast/Dockerfile"
          docker-no-cache: true
          docker-image: "cntk_lstm_forecast"
          docker-container: "CNTK_LSTM_FORECAST"
          docker-nvidia: true
          docker-volumes: "-v ~/singnet/.certs:/opt/singnet/.certs"
          daemon-version: ${CI_SNETD_VERSION}
          daemon-pk: ${PK_CNTK_LSTM_FORECAST}
  fbprophet-forecast:
    docker:
      - image: circleci/python:3.6.6-node
    steps:
      - checkout
      - ssh-deployment/deploy:
          ssh-host: ${SSH_HOST}
          ssh-user: ${SSH_USER}
          service-dir: "generic/fbprophet-forecast"
          mainnet-port: "7038"
          testnet-port: "7042"
          run-command: "python3 run_service.py --ssl --metering"
          docker-test-files: "Dockerfile, requirements.txt"
          docker-file-path: "generic/fbprophet-forecast/Dockerfile"
          docker-no-cache: true
          docker-image: "fbprophet_forecast"
          docker-container: "FBPROPHET_FORECAST"
          docker-nvidia: true
          docker-volumes: "-v ~/singnet/.certs:/opt/singnet/.certs"
          daemon-version: ${CI_SNETD_VERSION}
          daemon-pk: ${PK_FBPROPHET_FORECAST}

  testing:
    docker:
      - image: circleci/python:3.6.6-node
    steps:
        - ssh-deployment/test:
              ssh-host: ${SSH_HOST}
              ssh-user: ${SSH_USER}
              test-command: "sleep 20;source '/cntk/activate-cntk';python3 test_service.py auto"
              docker-container: "CNTK_NEXT_DAY_TREND"
        - ssh-deployment/test:
              ssh-host: ${SSH_HOST}
              ssh-user: ${SSH_USER}
              test-command: "sleep 20;source '/cntk/activate-cntk';python3 test_service.py auto"
              docker-container: "CNTK_LSTM_FORECAST"
        - ssh-deployment/test:
            ssh-host: ${SSH_HOST}
            ssh-user: ${SSH_USER}
            test-command: "sleep 20;python3 test_service.py auto"
            docker-container: "FBPROPHET_FORECAST"

workflows:
  build_deploy_ts_services:
    jobs:
      - cntk-next-day-trend
      - cntk-lstm-forecast
      - fbprophet-forecast
      - testing:
            requires:
              - cntk-next-day-trend
              - cntk-lstm-forecast
              - fbprophet-forecast